### ISSUE TITLE
Floating tabs

### ISSUE THREAD

**Issue by dimdimich** [tmhub/easytabs#11]
Can we implement such feature similiar to www.getintenso.com/demo/default/men/men-footwear/men-casual/man-bottom-shorts-combined-plimsolls.html ?

**Comment by 0m3r** [comment]
це типу щось такого http://leafo.net/sticky-kit/ ?
 @vovayatsyuk таке в аргенті використав

**Comment by dimdimich** [comment]
Yes looks nice but please discuss that with Vova if we should add it.

**Comment by dimdimich** [comment]
Is it possible or as an suggestion for future updates. Could you change the tabs  into floating tabs? So that all the informations are at the same page and not hidden as they are now. I think this could be a positive effect for SEO (more content at the product page). And so also for argentotheme.

**Comment by osseonews** [comment]
I also think you need to remove the "hidden" from the non-active tabs. Will be much better for SEO to keep those non-hidden. I am not sure why you hide them now.

**Comment by tangar76** [comment]
Implemented.
