### ISSUE TITLE
Problem with rendering javaScript generated content

### ISSUE THREAD

**Issue by rommmka** [tmhub/easytabs#18]
Yotpo reviews require empty div with data attributes to add their content with JS.
EasyTabs trim empty tags. 

> Add an option [checkbox] **Always render tab**

**Comment by tangar76** [comment]
![image](https://user-images.githubusercontent.com/13131588/29715945-21948f22-89b2-11e7-83b2-6da1377ea7de.png)
You can create custom tab. Add there `div` with style `display: none`. Than add necessary empty `div` for yotpo reviews.
