### ISSUE TITLE
Upgrading from 2.3.8 to 3.2.0: Invalid Method TM_EasyTabs_Block_Tabs::isExpandedLayout

### ISSUE THREAD

**Issue by m-overlund** [tmhub/easytabs#19]
I've just upgraded from 2.3.8 to 3.2.0.
After the usual Magento issues with sql changes not running, I'm now stuck at this error:

When i run the old frontend templates there are no issues, but as soon as i use the new ones i get this error report:

```
a:5:{i:0;s:67:"Invalid method TM_EasyTabs_Block_Tabs::isExpandedLayout(Array
(
)
)";i:1;s:4412:"#0 
[path]/public_html/app/design/frontend/base/default/template/tm/easytabs/tabs.phtml(14): Varien_Object->__call('isExpandedLayou...', Array)
```

Any ideas what could cause these issues?

**Comment by vovayatsyuk** [comment]
Hi,

Old layout update xml file could be the reason. Check if you have old [tm/easytabs.xml](https://github.com/tmhub/easytabs/blob/master/app/design/frontend/base/default/layout/tm/easytabs.xml) file in your theme. If you do - remove it.

**Comment by m-overlund** [comment]
thanks, helped a lot.
(Missed a change in the xml file)
